# Generated by Django 4.2.7 on 2023-11-19 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=1, verbose_name='购物车中商品数量')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车信息',
                'db_table': 'd_cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号')),
                ('order_total', models.IntegerField(default=0, verbose_name='商品总件数')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总金额')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('contact_name', models.CharField(default='', max_length=20, verbose_name='联系人')),
                ('contact_mobile', models.CharField(default='', max_length=11, verbose_name='联系电话')),
                ('pay_method', models.IntegerField(default=0, verbose_name='支付方式')),
                ('memo', models.CharField(default='', max_length=200, verbose_name='订单备注')),
                ('order_state', models.CharField(choices=[('paying', '待支付'), ('payed', '已支付'), ('shipping', '配送中'), ('complete', '订单结束'), ('cancel', '订单取消')], default='paying', max_length=20, verbose_name='用户')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'd_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goods', verbose_name='商品表')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order', verbose_name='订单主表')),
            ],
            options={
                'verbose_name': '订单商品信息',
                'verbose_name_plural': '订单商品信息',
                'db_table': 'd_order_goods',
                'managed': True,
            },
        ),
    ]
