# Generated by Django 3.1.5 on 2023-11-12 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('departname', models.CharField(max_length=30, verbose_name='部门名称')),
                ('createdate', models.DateTimeField(db_column='createDate', default=django.utils.timezone.now, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '部门信息',
                'db_table': 'DepartInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserExtraInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=30, verbose_name='用户名称')),
                ('truename', models.CharField(max_length=30, verbose_name='真实姓名')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='薪水')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
                ('status', models.CharField(max_length=1, verbose_name='状态')),
                ('createdate', models.DateTimeField(db_column='createDate', verbose_name='创建日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('depart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app4.departinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4.userbaseinfo')),
            ],
            options={
                'verbose_name': '人员扩展信息',
                'db_table': 'UserExtraInfo4',
                'managed': True,
            },
        ),
    ]
