# Generated by Django 3.1.5 on 2023-11-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_departinfo_userextrainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('skillname', models.CharField(max_length=30, verbose_name='特长')),
                ('createdate', models.DateTimeField(db_column='createDate', verbose_name='创建日期')),
                ('user', models.ManyToManyField(db_table='user_skill', to='app4.UserBaseInfo')),
            ],
            options={
                'verbose_name': '特长信息',
                'db_table': 'SkillInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('cardno', models.CharField(max_length=30, verbose_name='卡号')),
                ('bank', models.CharField(max_length=30, verbose_name='所属银行')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.userbaseinfo')),
            ],
            options={
                'verbose_name': '用户卡信息',
                'db_table': 'CardInfo',
                'managed': True,
            },
        ),
    ]
