# Generated by Django 4.2.7 on 2023-11-20 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="slide", verbose_name="轮播图片")),
                ("sort", models.IntegerField(default=0, verbose_name="排列顺序")),
                (
                    "create_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="添加时间"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="goods.goods",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "首页轮播",
                "verbose_name_plural": "首页轮播",
                "db_table": "d_slide",
            },
        ),
    ]
